# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh2YRNl-65GgiBob1I4s-qs_nAywvbOD
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

# Sample Dataset
data = {
    "Attendance": ["High", "High", "Medium", "Low", "Low", "Medium", "High", "Low"],
    "Assignment": ["Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No"],
    "StudyHours": ["High", "Medium", "High", "Low", "Medium", "High", "Medium", "Low"],
    "InternalMarks": ["High", "Medium", "High", "Low", "Medium", "Medium", "High", "Low"],
    "Result": ["Pass", "Pass", "Pass", "Fail", "Fail", "Pass", "Pass", "Fail"]
}

df = pd.DataFrame(data)

print("Dataset:")
print(df)

# Encode categorical data
encoders = {}
for col in df.columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

# Features and Target
X = df.drop("Result", axis=1)
y = df["Result"]

# Train ID3 Decision Tree
model = DecisionTreeClassifier(criterion="entropy")
model.fit(X, y)

# New Sample
new_sample = pd.DataFrame({
    "Attendance": [encoders["Attendance"].transform(["Medium"])[0]],
    "Assignment": [encoders["Assignment"].transform(["Yes"])[0]],
    "StudyHours": [encoders["StudyHours"].transform(["High"])[0]],
    "InternalMarks": [encoders["InternalMarks"].transform(["Medium"])[0]]
})

# Prediction
prediction = model.predict(new_sample)

print("\nNew Sample:")
print({
    "Attendance": "Medium",
    "Assignment": "Yes",
    "StudyHours": "High",
    "InternalMarks": "Medium"
})

print("Predicted Result:", encoders["Result"].inverse_transform(prediction)[0])

# Decision Tree Structure
print("\nDecision Tree Structure")
print("-----------------------")
print("""
                Attendance
               /          \\
           High       Medium/Low
            |              |
          Pass        StudyHours
                     /          \\
                  High          Low
                   |             |
             Assignment    InternalMarks
              /      \\       /        \\
            Yes      No    High      Low
             |        |      |         |
           Pass     Fail   Pass      Fail
""")